version: "3"

services:
  web:
    image: web
    restart: on-failure
    build:
      context: ./
      dockerfile: web.dockerfile
    environment:
      - URL=0.0.0.0
      - PORT=5000
    ports:
      - 5000:5000/tcp
    volumes:
      - ./sqlite:/sibur/sqlite/
  nginx:
    depends_on:
      - web
    image: nginx
    restart: always
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/jpepper/domain.crt:/etc/nginx/domain.crt
      - /home/jpepper/key.pem:/etc/nginx/key.pem
  sender:
    depends_on:
      - nginx
    image: sender
    restart: on-failure
    build:
      context: ./
      dockerfile: sender.dockerfile
    environment:
      - URL=0.0.0.0
      - PORT=5000
      - WEB_URL=http://51.250.48.50
    volumes:
      - ./sqlite:/sibur/sqlite/
